# Generated by Django 5.2.5 on 2025-08-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_blogpost_body_blogpost_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='video_url',
        ),
    ]
