# Generated by Django 5.2.5 on 2025-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
