# Generated by Django 6.0.3 on 2026-04-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/vposts/')),
                ('video_url', models.URLField(blank=True, help_text='Alternatively, provide a video link (e.g. TikTok, YouTube, etc.)', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
