# Generated by Django 6.0.3 on 2026-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='clients/logos/'),
        ),
    ]
