# Generated by Django 6.0.3 on 2026-04-10 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_adminnotification_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Sending', 'Sending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Draft', max_length=20),
        ),
    ]
