# Generated by Django 6.0.3 on 2026-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_telegramtag_telegramcampaign_telegramuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappointment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='telegram/payments/'),
        ),
        migrations.AddField(
            model_name='telegramappointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='current_state',
            field=models.CharField(default='idle', max_length=100),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='state_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='telegramappointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
