# Generated by Django 6.0.3 on 2026-04-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_telegramappointment_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramappointment',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
