# Generated by Django 6.0.3 on 2026-04-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_patient_product_alter_socialfeedpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='telegramappointment',
            name='doctor_assigned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramappointment',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Clinic notes for staff', null=True),
        ),
        migrations.AddField(
            model_name='telegramappointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Patient notes from Telegram', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
