# Generated by Django 6.0.3 on 2026-04-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_contactmessage_address_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(help_text='Badge or System ID', max_length=50, unique=True)),
                ('position', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Expertise (e.g. Cardiology)', max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
