# Generated by Django 6.0.3 on 2026-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, help_text='e.g. O+, A-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
