# Generated by Django 6.0.3 on 2026-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_patient_age_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='gender',
            field=models.CharField(blank=True, help_text='Requested for Patient registration', max_length=20, null=True),
        ),
    ]
