# Generated by Django 6.0.3 on 2026-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_inventoryitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Cardiology, Dental', max_length=100),
        ),
    ]
